### ISSUE TITLE
Cannot connect with AWS-SDK

### ISSUE THREAD

**Issue by DanaGoldStar** [jubos/fake-s3#32] opened 2013-05-08 18:31 UTC
I've tried everything connecting to aws-sdk with no luck as yet. Solely connection refused attempts.

I am set up running two vagrant machines. One running fake-s3, which I can verify is available by navigating to 10.0.10.6 (where it is located) and viewing the XML bucket result output.

When I attempt to connect from my rails application. Or simply the rails console using the following. 

``` ruby
s3 = AWS::S3.new({:access_key_id => "123", :secret_access_key => "abc", :s3_endpoint => "10.0.10.6",
 :s3_force_path_style => true, :s3_port => 4567, :use_ssl => false})
```

The AWS::S3 object gets created bucket s3.buckets.each return a connection error. In addition to the force_path_styles. I've tried using xip.io as a tld to route back to my bucket but no luck as well. I could not seem to find the s3_endpoint configuration option under the aws:sdk source as well, but I may not have been looking correctly.

Has anyone had any luck with this?

**Comment by tielur** [comment] 2015-04-22 19:13
@georgeportillo and for anyone else using the [aws-sdk-js](https://github.com/aws/aws-sdk-js) library. This is working for me:

```javascript
var config = {
  accessKeyId: "123",
  secretAccessKey: "abc",
  endpoint: "localhost:3001",
  sslEnabled: false,
  s3ForcePathStyle: true
};
AWS.config.update(config);

var s3 = new AWS.S3({params: {Bucket: 'myBucket'}});
```

**Comment by jiminikiz** [comment] 2016-10-10 21:42
This error occurs when you pass in invalid credentials.

**Comment by pickhardt** [comment] 2017-01-08 01:34
Closing because it seems this has been resolved - invalid credentials was the problem. If it wasn't, just let me know exactly what I should do to reproduce and I can look into it.

**Closed by pickhardt** 2017-01-08 01:34 UTC

**Comment by khessels** [comment] 2018-01-18 15:10
Just had the same thing, My uploaded content would be available like normal, but as soon as i would use the aws-sdk to manipulate files i would receive the same ENETUNREACH error. The whole day looking for a problem. Next day it magically started working again. Turns out that it was a problem with amazon.
